#!/bin/sh

# Define the project subdirectory
PROJECT_DIR="event-scraper"

echo "Starting pre-push checks!"

# Navigate to the project subdirectory
cd "$PROJECT_DIR"

# Run npm build
echo "Building project in $PROJECT_DIR..."
npm run build

# Check if npm build succeeded
if [ $? -ne 0 ]; then
  echo "`npm run build` failed in $PROJECT_DIR. Aborting push."
  exit 1
fi

# Run npm test
echo "Running tests in $PROJECT_DIR..."
npm run test

# Check if npm test succeeded
if [ $? -ne 0 ]; then
  echo "`npm run test` failed in $PROJECT_DIR. Aborting push."
  exit 1
fi

echo "All pre-push checks succeeded. Proceeding with push.\\n"

exit 0