#!/bin/sh

SCRAPER_PROJECT_DIR="event-scraper"
CLIENT_PROJECT_DIR="client"

echo "Starting pre-push checks!"
cd "$SCRAPER_PROJECT_DIR"

# Run npm build
echo "Building project in $SCRAPER_PROJECT_DIR..."
npm run build
if [ $? -ne 0 ]; then
  echo "`npm run build` failed in $SCRAPER_PROJECT_DIR. Aborting push."
  exit 1
fi

# Run npm test
echo "Running tests in $SCRAPER_PROJECT_DIR..."
npm run test
if [ $? -ne 0 ]; then
  echo "`npm run test` failed in $SCRAPER_PROJECT_DIR. Aborting push."
  exit 1
fi

# Navigate to the client dir  
cd "../$CLIENT_PROJECT_DIR"

# Run npm build
echo "Building project in $CLIENT_PROJECT_DIR..."
npm run build
if [ $? -ne 0 ]; then
  echo "`npm run build` failed in $CLIENT_PROJECT_DIR. Aborting push."
  exit 1
fi

echo "All pre-push checks succeeded. Proceeding with push.\\n"

exit 0